from __future__ import annotations

from typing import List

from app.db.database import SessionLocal
from app.db.repositories.arxiv_repository import ArxivRepository
from app.utils.logger import logger


def get_recent_hot_phrases(limit: int = 4) -> List[str]:
    """
    Fetch the most recent hot phrases generated by the crawler.

    Args:
        limit: Max number of phrases to return.
    """
    session = SessionLocal()
    try:
        repository = ArxivRepository(session)
        phrases = repository.list_hot_phrases(limit=limit)
        if phrases:
            logger.info("Loaded %d hot phrases from DB (limit=%d).", len(phrases), limit)
        else:
            logger.info("No hot phrases available in DB.")
        return phrases
    except Exception as exc:  # pragma: no cover - defensive logging
        logger.warning("Failed to load hot phrases from DB: %s", exc)
        return []
    finally:
        session.close()


